name: Scheduled Email Sender

on:
  schedule:
    - cron: '*/20 * * * *'  
  workflow_dispatch:  

jobs:
  send-email:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Send Email
        env:
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
          RECIPIENT_EMAIL: ${{ secrets.RECIPIENT_EMAIL }}
        run: python send_email.py

      - name: Notify on Failure
        if: failure()
        uses: actions/github-script@v6
        with:
          script: |
            core.warning('Email failed to send!')